# Generated by Django 5.2.4 on 2025-07-17 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID')),
                ('event_type', models.CharField(choices=[('message', 'Сообщение'), ('command', 'Команда'), ('callback', 'Callback'), ('notify', 'Уведомление'), ('error', 'Ошибка')], max_length=16, verbose_name='Тип события')),
                ('request_text', models.TextField(blank=True, verbose_name='Текст запроса')),
                ('response_text', models.TextField(blank=True, verbose_name='Текст ответа')),
                ('success', models.BooleanField(blank=True, null=True, verbose_name='Успех')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='Сырые данные')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог Telegram-бота',
                'verbose_name_plural': 'Логи Telegram-бота',
                'ordering': ['-created_at'],
            },
        ),
    ]
