# Generated by Django 5.2.4 on 2025-07-18 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='botlog',
            name='event_type',
            field=models.CharField(choices=[('message', 'Сообщение'), ('command', 'Команда'), ('callback', 'Callback'), ('notify', 'Уведомление'), ('error', 'Ошибка')], help_text='Категория события в боте', max_length=16, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='botlog',
            name='raw_data',
            field=models.JSONField(blank=True, help_text='Дополнительные данные в формате JSON', null=True, verbose_name='Сырые данные'),
        ),
        migrations.AlterField(
            model_name='botlog',
            name='request_text',
            field=models.TextField(blank=True, help_text='Сообщение или команда от пользователя', verbose_name='Текст запроса'),
        ),
        migrations.AlterField(
            model_name='botlog',
            name='response_text',
            field=models.TextField(blank=True, help_text='Ответ бота пользователю', verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='botlog',
            name='success',
            field=models.BooleanField(blank=True, help_text='True - успешно обработано, False - ошибка', null=True, verbose_name='Успех'),
        ),
        migrations.AlterField(
            model_name='botlog',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, help_text='ID пользователя в Telegram', null=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='botlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Пользователь сайта (если привязан)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='botlog',
            index=models.Index(fields=['telegram_id'], name='bot_api_bot_telegra_89b0ae_idx'),
        ),
        migrations.AddIndex(
            model_name='botlog',
            index=models.Index(fields=['event_type'], name='bot_api_bot_event_t_a424d4_idx'),
        ),
        migrations.AddIndex(
            model_name='botlog',
            index=models.Index(fields=['created_at'], name='bot_api_bot_created_e00634_idx'),
        ),
        migrations.AddIndex(
            model_name='botlog',
            index=models.Index(fields=['success'], name='bot_api_bot_success_ab315a_idx'),
        ),
    ]
