# Generated by Django 5.2.1 on 2025-07-09 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_review', models.DateField(verbose_name='Дата следующего повторения')),
                ('interval', models.PositiveIntegerField(default=1, verbose_name='Интервал (дней)')),
                ('repetition', models.PositiveIntegerField(default=0, verbose_name='Номер повторения')),
                ('ef', models.FloatField(default=2.5, verbose_name='Эффективность (SM-2)')),
                ('last_result', models.BooleanField(blank=True, null=True, verbose_name='Последний результат (успех)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='cards.card', verbose_name='Карточка')),
            ],
        ),
    ]
